### ISSUE TITLE
User can generate random genres.

### ISSUE THREAD

**Issue by leanne-vu** [leanne-vu/ajax-project#1]
## 💰 Motivation

Users will be able to discover new musical genres.

## 📐 Plan

Users may generate random musical genres with a press of a button, genres that the user select will populate a selections list.

## 🖼️ Wireframes

![user can view their entries mobile](https://www.figma.com/file/etaSXLihdSMHiwIc9ANzN9/Leanne-Vu-ajax-project?node-id=1%3A3)
![user can view their entries desktop](https://www.figma.com/file/etaSXLihdSMHiwIc9ANzN9/Leanne-Vu-ajax-project?node-id=1%3A4)

## ✅ Task List

- [ ] Add a sibling `div[data-view="generator"]` to the HTML.
- [ ] Add an empty unordered list to the `div[data-view="generator"]` element in the HTML.
- [ ] Add some dummy musical genres to the unordered list in the HTML and style them to match the wireframe.
- [ ] Check that the list looks good on both mobile and desktop screens.
- [ ] Add a sibling 'div[data-view="selections"]' to the HTML.
- [ ] Define a function that takes a single `genre` object and returns a DOM tree that matches one of the example selections in the HTML.
- [ ] Use a loop to create a DOM tree for each genre in the data model and append it to the page when the `'DOMContentLoaded'` event is fired.
- [ ] Remove the example HTML genres once the user's genres are successfully being appended to the DOM on page load.
- [ ] Add a navigation item to the navbar for the home generator.
- [ ] Add an anchor to the entries view that shows the selections list.
- [ ] Ensure that selecting a genre also creates a new DOM tree for it and adds it to the page.
- [ ] Ensure that refreshing the pages shows the same view as before refreshing.
- [ ] Clean up all unnecessary styling.
- [ ] Test the app some more in a private browsing tab.
- [ ] Fix all errors.
