### ISSUE TITLE
User can delete genres and entries.

### ISSUE THREAD

**Issue by leanne-vu** [leanne-vu/ajax-project#4]
## 💰 Motivation

User will be able to delete unwanted genres or entries.
## 📐 Plan

Add a functional delete button to both selections list and individual genre entries list.

## 🖼️ Wireframes
**User can view the generator and selections mobile**
https://www.figma.com/file/etaSXLihdSMHiwIc9ANzN9/Leanne-Vu-ajax-project?node-id=1%3A3
**User can view the generator and selections desktop**
https://www.figma.com/file/etaSXLihdSMHiwIc9ANzN9/Leanne-Vu-ajax-project?node-id=1%3A4

## ✅ Task List

- [x] Add a delete icon for each individual entry
- [x] Remove entry from data model and the entry's DOM tree from the page if the user clicks on icon.
- [x] Add a delete icon for each musical genre selection. 
- [x] Add a modal to the selections page
- [x]  Show a confirmation modal when the user clicks the delete icon for genre.
- [x] Hide the modal if the user clicks Cancel.
- [x] If user clicks confirm, delete entire genre and its entries DOM tree from the page and data model.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
